language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"

# command to run tests
script: nosetests -v

notifications:
    slack: beylsp:ksj5Wk4lvPhMvo7Iy1UYdALL

env:
# configuration: Production, Development or Testing
- CONFIG=Testing
